"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import StudentsShell from "../students/StudentsShell";
import { initialStudents,readStudents,Student } from "../students/student-data";
import { demoToday,initialLessons,Lesson,LessonStatus,readLessons,writeLessons } from "./lesson-data";
import { conflictsFor } from "./series-data";
import { useFinancialData } from "../payments/use-financial-data";
import { financeLabel, savedLessonPrice, money } from "../payments/payment-calculation";
import {completeLessonTransaction,setLessonStatusTransaction} from "../../lib/firebase-operations";
import {saveDocument} from "../../lib/firestore-store";
import "../students/students.css";
import "./schedule.css";
import LessonMenu from "./LessonMenu";

const fullDayNames=["Воскресенье","Понедельник","Вторник","Среда","Четверг","Пятница","Суббота"];
const monthNames=["января","февраля","марта","апреля","мая","июня","июля","августа","сентября","октября","ноября","декабря"];
const monthTitles=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"];
const statusLabels:Record<LessonStatus,string>={scheduled:"Запланировано",completed:"Проведено",cancelled:"Отменено",rescheduled:"Перенесено"};
const iso=(date:Date)=>{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`};
const fromIso=(value:string)=>{const [y,m,d]=value.split("-").map(Number);return new Date(y,m-1,d)};
const formatDate=(value:string)=>{const date=fromIso(value);return `${date.getDate()} ${monthNames[date.getMonth()]}`};

type Modal={kind:"add"}|{kind:"complete"|"cancel"|"move";lesson:Lesson}|null;
type ScopeChoice={kind:"cancel";lesson:Lesson}|{kind:"move";lesson:Lesson;date:string;time:string}|null;

export default function SchedulePage(){
 const finance=useFinancialData();
 const [students,setStudents]=useState<Student[]>(initialStudents),[lessons,setLessons]=useState<Lesson[]>(initialLessons),[selected,setSelected]=useState(demoToday),[modal,setModal]=useState<Modal>(null),[scopeChoice,setScopeChoice]=useState<ScopeChoice>(null),[toast,setToast]=useState("");
 useEffect(()=>{const load=()=>{setStudents(readStudents());setLessons(readLessons())},timer=window.setTimeout(()=>{load();if(new URLSearchParams(window.location.search).get("add")==="1")setModal({kind:"add"})},0);window.addEventListener("tutorflow-data-change",load);return()=>{window.clearTimeout(timer);window.removeEventListener("tutorflow-data-change",load)}},[]);
 const selectedDate=fromIso(selected),monthStart=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1),offset=(monthStart.getDay()+6)%7;
 const calendarDays=Array.from({length:42},(_,index)=>{const date=new Date(monthStart);date.setDate(index-offset+1);return date});
 const visible=useMemo(()=>lessons.filter(item=>item.date===selected).sort((a,b)=>a.time.localeCompare(b.time)),[lessons,selected]);
 const todayDate=fromIso(demoToday),todayLessons=lessons.filter(item=>item.date===demoToday),todayCompleted=todayLessons.filter(item=>item.status==="completed").length,todayCancelled=todayLessons.filter(item=>item.status==="cancelled").length;
 const notify=(value:string)=>{setToast(value);window.setTimeout(()=>setToast(""),2300)};
 const persist=(next:Lesson[])=>{setLessons(next);writeLessons(next)};
 const shiftMonth=(amount:number)=>{const date=fromIso(selected),day=date.getDate();date.setDate(1);date.setMonth(date.getMonth()+amount);date.setDate(Math.min(day,new Date(date.getFullYear(),date.getMonth()+1,0).getDate()));setSelected(iso(date))};
 const complete=async(lesson:Lesson)=>{if(lesson.status==="completed")return;const student=students.find(item=>item.id===lesson.studentId);if(!student)return;try{const changed=await completeLessonTransaction(lesson.id,student.id);if(!changed){notify("Занятие уже было проведено");return}setModal({kind:"complete",lesson:{...changed,id:lesson.id}})}catch{notify("Не удалось провести занятие. Попробуйте ещё раз.")}};
 const cancelLesson=async(lesson:Lesson,following=false)=>{try{const affected=lessons.filter(item=>item.id===lesson.id||following&&item.seriesId===lesson.seriesId&&item.date>=lesson.date&&item.status!=="completed");await Promise.all(affected.map(item=>setLessonStatusTransaction(item.id,item.studentId,"cancelled")));setModal(null);setScopeChoice(null);notify("Занятие отменено")}catch(error){notify(error instanceof Error?error.message:"Не удалось отменить занятие")}};
 const moveLesson=(lesson:Lesson,date:string,time:string,following=false)=>{const affected=following?lessons.filter(item=>item.seriesId===lesson.seriesId&&item.date>=lesson.date&&(item.status==="scheduled"||item.status==="rescheduled")):[lesson],ignore=affected.map(item=>item.id),dayShift=Math.round((fromIso(date).getTime()-fromIso(lesson.date).getTime())/86400000),changed=affected.map(item=>{const next=fromIso(item.date);next.setDate(next.getDate()+dayShift);return{...item,date:iso(next),time,status:"rescheduled" as const,seriesOverride:!following}}),conflict=changed.flatMap(item=>conflictsFor(item,lessons,ignore))[0];if(conflict){window.alert(`Это время уже занято: ${conflict.date}, ${conflict.time}`);return}persist(lessons.map(item=>changed.find(next=>next.id===item.id)??item));setSelected(date);setModal(null);setScopeChoice(null);notify(following?"Будущие занятия перенесены":"Занятие перенесено")};
 const studentFor=(lesson:Lesson)=>students.find(item=>item.id===lesson.studentId);

 return <StudentsShell active="Расписание" toast={toast}><header className="students-header schedule-header"><div><h1>Расписание</h1><p>Занятия и планы на месяц</p></div><button className="students-add" onClick={()=>setModal({kind:"add"})}>+ Добавить занятие</button></header>
 <div className="schedule-layout"><section className="month-panel"><div className="month-controls"><button aria-label="Предыдущий месяц" onClick={()=>shiftMonth(-1)}>←</button><h2>{monthTitles[selectedDate.getMonth()]} {selectedDate.getFullYear()}</h2><button aria-label="Следующий месяц" onClick={()=>shiftMonth(1)}>→</button><button className="today-button" onClick={()=>setSelected(iso(new Date()))}>Сегодня</button></div><div className="calendar-weekdays">{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(day=><span key={day}>{day}</span>)}</div><div className="month-grid">{calendarDays.map(date=>{const value=iso(date),count=lessons.filter(item=>item.date===value).length,outside=date.getMonth()!==selectedDate.getMonth(),today=value===iso(new Date());return <button key={value} className={`${value===selected?"selected ":""}${outside?"outside ":""}${today?"today":""}`} onClick={()=>setSelected(value)}><b>{date.getDate()}</b>{count>0&&<span className="lesson-count">• {count}</span>}</button>})}</div><div className="today-summary"><img src="/asset-lavender-sprig.png" alt="" aria-hidden="true"/><div className="today-summary-title"><strong>Сегодня</strong><span>{todayDate.getDate()} {monthNames[todayDate.getMonth()]}, {fullDayNames[todayDate.getDay()].toLocaleLowerCase("ru")}</span></div><div className="today-summary-stat"><b>{todayLessons.length}</b><span>занятия</span></div><div className="today-summary-stat"><b>{todayCompleted}</b><span>проведено</span></div><div className="today-summary-stat"><b>{todayCancelled}</b><span>отменено</span></div></div></section>
 <aside className="day-panel"><div className="day-panel-heading"><h2>{fullDayNames[selectedDate.getDay()]}, {formatDate(selected)}</h2><b>{visible.length} {visible.length===1?"занятие":visible.length>=2&&visible.length<=4?"занятия":"занятий"}</b></div>{visible.length?<div className="schedule-list">{visible.map((lesson,index)=>{const student=studentFor(lesson);if(!student)return null;return <article className="schedule-card" key={lesson.id}><div className="schedule-time"><strong>{lesson.time}</strong></div><div className={`student-list-avatar avatar-${index%4}`}>{student.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div className="schedule-student"><strong>{student.name}</strong><span>{student.grade} · {lesson.duration} мин {lesson.seriesId&&<em className="series-mark">↻ Еженедельно</em>}</span></div><div className="schedule-payment"><small>{financeLabel(finance.forStudent(student.id))}</small></div><span className={`lesson-status ${lesson.status}`}>{statusLabels[lesson.status]}</span>{<LessonMenu label={`Действия: ${student.name}`}>{lesson.status!=="completed"&&<button onClick={()=>complete(lesson)}>Проведено</button>}{lesson.status!=="cancelled"&&<button onClick={()=>setModal({kind:"cancel",lesson})}>Отменить</button>}{(lesson.status==="scheduled"||lesson.status==="rescheduled")&&<button onClick={()=>setModal({kind:"move",lesson})}>Перенести</button>}</LessonMenu>}</article>})}</div>:<div className="schedule-empty"><h2>На этот день занятий нет</h2><img src="/asset-lavender-sprig.png" alt=""/><button className="students-add" onClick={()=>setModal({kind:"add"})}>+ Добавить занятие</button></div>}</aside></div>
 {modal?.kind==="add"&&<AddLesson students={students.filter(student=>!student.archived)} date={selected} onCancel={()=>setModal(null)} onSave={lesson=>{const conflict=conflictsFor(lesson,lessons)[0];if(conflict){window.alert(`Это время уже занято: ${conflict.date}, ${conflict.time}`);return}persist([...lessons,lesson]);setSelected(lesson.date);setModal(null);notify("Занятие добавлено")}}/>}
 {modal?.kind==="complete"&&<CompleteLesson lesson={modal.lesson} student={studentFor(modal.lesson)!} onSave={async note=>{try{await saveDocument("lessons",{id:modal.lesson.id,note});setModal(null);notify("Заметка сохранена")}catch{notify("Не удалось сохранить заметку")}}} onSkip={()=>setModal(null)}/>}
 {modal?.kind==="cancel"&&<ConfirmCancel lesson={modal.lesson} student={studentFor(modal.lesson)!} onBack={()=>setModal(null)} onConfirm={()=>modal.lesson.seriesId?setScopeChoice({kind:"cancel",lesson:modal.lesson}):cancelLesson(modal.lesson)}/>}
 {modal?.kind==="move"&&<MoveLesson lesson={modal.lesson} onCancel={()=>setModal(null)} onSave={(date,time)=>modal.lesson.seriesId?setScopeChoice({kind:"move",lesson:modal.lesson,date,time}):moveLesson(modal.lesson,date,time)}/>}
 {scopeChoice&&<ScopeModal action={scopeChoice.kind==="cancel"?"отменить":"изменить"} onCancel={()=>setScopeChoice(null)} onOne={()=>scopeChoice.kind==="cancel"?cancelLesson(scopeChoice.lesson):moveLesson(scopeChoice.lesson,scopeChoice.date,scopeChoice.time)} onFollowing={()=>scopeChoice.kind==="cancel"?cancelLesson(scopeChoice.lesson,true):moveLesson(scopeChoice.lesson,scopeChoice.date,scopeChoice.time,true)}/>}
 </StudentsShell>
}

function ModalFrame({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="student-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="schedule-modal" role="dialog" aria-modal="true"><header><h2>{title}</h2><button aria-label="Закрыть" onClick={onClose}>×</button></header>{children}</section></div>}
function AddLesson({students,date,onSave,onCancel}:{students:Student[];date:string;onSave:(lesson:Lesson)=>void;onCancel:()=>void}){const [studentId,setStudentId]=useState(students[0]?.id??""),[lessonDate,setDate]=useState(date),[time,setTime]=useState("15:00"),[duration,setDuration]=useState<Lesson["duration"]>(60);const submit=(event:FormEvent)=>{event.preventDefault();onSave({id:`lesson-${Date.now()}`,studentId,date:lessonDate,time,duration,status:"scheduled",paid:true,note:"",charged:false})};return <ModalFrame title="Добавить занятие" onClose={onCancel}><form className="schedule-form" onSubmit={submit}><label>Ученик<select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(student=><option value={student.id} key={student.id}>{student.name}</option>)}</select></label><div className="form-row"><label>Дата<input required type="date" value={lessonDate} onChange={e=>setDate(e.target.value)}/></label><label>Время<input required type="text" inputMode="numeric" pattern="(?:[01][0-9]|2[0-3]):[0-5][0-9]" placeholder="15:00" title="Введите время в 24-часовом формате ЧЧ:ММ" value={time} onChange={e=>setTime(e.target.value)}/></label></div><label>Продолжительность<select value={duration} onChange={e=>setDuration(Number(e.target.value) as Lesson["duration"])}>{[30,40,45,60,90].map(value=><option value={value} key={value}>{value} минут</option>)}</select></label><div className="modal-actions"><button type="button" onClick={onCancel}>Отмена</button><button className="form-save">Сохранить</button></div></form></ModalFrame>}
function CompleteLesson({lesson,student,onSave,onSkip}:{lesson:Lesson;student:Student;onSave:(note:string)=>void;onSkip:()=>void}){const [note,setNote]=useState(lesson.note??"");return <ModalFrame title="Занятие проведено!" onClose={onSkip}><div className="completed-summary"><div className="student-list-avatar avatar-0">{student.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><h3>{student.name}</h3><p>{formatDate(lesson.date)} · {lesson.time}</p></div></div><p>Начислено за занятие: <b>{savedLessonPrice(lesson)===null?"Уточните историческую стоимость":money(savedLessonPrice(lesson)!)}</b></p><label className="note-label">Заметка себе <span>(необязательно)</span><textarea placeholder="Например: повторить Past Simple" value={note} onChange={e=>setNote(e.target.value)}/></label><div className="modal-actions"><button onClick={onSkip}>Пропустить</button><button className="form-save" onClick={()=>onSave(note)}>Сохранить</button></div></ModalFrame>}
function ConfirmCancel({lesson,student,onBack,onConfirm}:{lesson:Lesson;student:Student;onBack:()=>void;onConfirm:()=>void}){return <ModalFrame title="Отменить занятие?" onClose={onBack}><p className="confirm-copy">Отменить занятие с <b>{student.name}</b><br/>{formatDate(lesson.date)} в {lesson.time}?</p><div className="modal-actions"><button onClick={onBack}>Назад</button><button className="danger-button" onClick={onConfirm}>Отменить занятие</button></div></ModalFrame>}
function MoveLesson({lesson,onCancel,onSave}:{lesson:Lesson;onCancel:()=>void;onSave:(date:string,time:string)=>void}){const [date,setDate]=useState(lesson.date),[time,setTime]=useState(lesson.time);return <ModalFrame title="Перенести занятие" onClose={onCancel}><form className="schedule-form" onSubmit={event=>{event.preventDefault();onSave(date,time)}}><label>Новая дата<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Новое время<input required type="text" inputMode="numeric" pattern="(?:[01][0-9]|2[0-3]):[0-5][0-9]" placeholder="15:00" title="Введите время в 24-часовом формате ЧЧ:ММ" value={time} onChange={e=>setTime(e.target.value)}/></label><div className="modal-actions"><button type="button" onClick={onCancel}>Отмена</button><button className="form-save">Сохранить</button></div></form></ModalFrame>}
function ScopeModal({action,onCancel,onOne,onFollowing}:{action:"отменить"|"изменить";onCancel:()=>void;onOne:()=>void;onFollowing:()=>void}){return <ModalFrame title={action==="отменить"?"Что отменить?":"Что изменить?"} onClose={onCancel}><p>Выберите, к каким занятиям серии применить действие.</p><div className="scope-actions"><button onClick={onOne}>Только это занятие</button><button className="form-save" onClick={onFollowing}>Это и все следующие</button><button onClick={onCancel}>Отмена</button></div></ModalFrame>}
