"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import StudentsShell from "../StudentsShell";
import StudentForm from "../StudentForm";
import { readStudents,Student,writeStudents } from "../student-data";
import { Lesson,readLessons } from "../../schedule/lesson-data";
import { Payment,readPayments } from "../../payments/payment-data";
import "../students.css";

export default function StudentDetail(){
 const [student,setStudent]=useState<Student|null>(null),[lessons,setLessons]=useState<Lesson[]>([]),[payments,setPayments]=useState<Payment[]>([]),[editing,setEditing]=useState(false),[toast,setToast]=useState("");
 useEffect(()=>{const timeout=window.setTimeout(()=>{const id=decodeURIComponent(window.location.pathname.split("/").filter(Boolean).pop()||"");setStudent(readStudents().find(s=>s.id===id)??null);setLessons(readLessons().filter(lesson=>lesson.studentId===id).sort((a,b)=>`${b.date} ${b.time}`.localeCompare(`${a.date} ${a.time}`)));setPayments(readPayments().filter(payment=>payment.studentId===id).sort((a,b)=>b.date.localeCompare(a.date)))},0);return()=>window.clearTimeout(timeout)},[]);
 const save=(value:Student)=>{const all=readStudents(),next=all.some(s=>s.id===value.id)?all.map(s=>s.id===value.id?value:s):[...all,value];writeStudents(next);setStudent(value);setEditing(false);setToast("Данные ученика обновлены");window.setTimeout(()=>setToast(""),2300)};
 const tone=(n:number)=>n>=5?"balance-good":n>=2?"balance-warn":"balance-low";
 if(!student)return <StudentsShell><Link className="student-back" href="/students">← К списку учеников</Link><div className="detail-card">Ученик не найден</div></StudentsShell>;
 return <StudentsShell toast={toast}><Link className="student-back" href="/students">← К списку учеников</Link><section className="detail-card"><div className="detail-top"><div><h1>{student.name}</h1><span className="student-grade">{student.grade||"Класс не указан"}</span></div><button className="edit-button" onClick={()=>setEditing(true)}>Редактировать</button></div><div className="detail-grid"><div className="detail-item"><span>Класс</span><strong>{student.grade||"—"}</strong></div><div className="detail-item"><span>Стоимость занятия</span><strong>{student.price.toLocaleString("ru-RU")} ₽</strong></div><div className="detail-item"><span>Остаток</span><b className={`balance-pill ${tone(student.balance)}`}>{student.balance}</b></div><div className="detail-item"><span>Дни занятий</span><strong>{student.days||"—"}</strong></div></div><div className="detail-comment"><b>Комментарий</b><p>{student.comment||"Без комментария"}</p></div></section><div className="detail-placeholders"><section className="placeholder-card lesson-history"><h2>История занятий</h2>{lessons.length?lessons.map(lesson=><article key={lesson.id}><div><strong>{new Date(`${lesson.date}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"long"})}, {lesson.time}</strong><span className={`history-status ${lesson.status}`}>{lesson.status==="completed"?"Проведено":lesson.status==="cancelled"?"Отменено":lesson.status==="rescheduled"?"Перенесено":"Запланировано"}</span></div>{lesson.note&&<p>{lesson.note}</p>}</article>):<p>Занятий пока нет.</p>}</section><section className="placeholder-card student-payments"><h2>Оплаты</h2>{payments.length?payments.map(payment=><article key={payment.id}><strong>{new Date(`${payment.date}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"})}</strong><span>{payment.lessonCount} занятий · {payment.lessonPrice.toLocaleString("ru-RU")} ₽ / занятие</span><b>{payment.amount.toLocaleString("ru-RU")} ₽</b></article>):<p>Пока нет оплат.</p>}</section></div>{editing&&<StudentForm title="Редактировать ученика" initial={student} onSave={save} onCancel={()=>setEditing(false)}/>}</StudentsShell>
}
