"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import StudentsShell from "../students/StudentsShell";
import { initialStudents,readStudents,Student } from "../students/student-data";
import {currentLessonPrice} from "../students/student-price";
import { Payment,readPayments } from "./payment-data";
import {deletePaymentTransaction,savePaymentTransaction} from "../../lib/firebase-operations";
import "../students/students.css";
import "./payments.css";

const months=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"];
const isoToday=()=>{const date=new Date(),y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`};
const money=(value:number)=>`${value.toLocaleString("ru-RU")} ₽`;
type Dialog={kind:"add";studentId?:string}|{kind:"edit"|"delete";payment:Payment}|null;

export default function PaymentsPage(){
 const now=new Date(),[students,setStudents]=useState<Student[]>(initialStudents),[payments,setPayments]=useState<Payment[]>([]),[month,setMonth]=useState(now.getMonth()),[year,setYear]=useState(now.getFullYear()),[dialog,setDialog]=useState<Dialog>(null),[toast,setToast]=useState("");
 useEffect(()=>{const load=()=>{setStudents(readStudents());setPayments(readPayments())},timer=window.setTimeout(load,0);window.addEventListener("tutorflow-data-change",load);return()=>{window.clearTimeout(timer);window.removeEventListener("tutorflow-data-change",load)}},[]);
 const monthly=useMemo(()=>payments.filter(payment=>{const date=new Date(`${payment.date}T12:00:00`);return date.getMonth()===month&&date.getFullYear()===year}).sort((a,b)=>b.date.localeCompare(a.date)),[payments,month,year]);
 const received=monthly.reduce((sum,payment)=>sum+payment.amount,0),paidLessons=monthly.reduce((sum,payment)=>sum+payment.lessonCount,0),needPayment=students.filter(student=>student.balance===0).length;
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2300)};
 const save=async(payment:Payment,previous?:Payment)=>{try{await savePaymentTransaction(payment);setDialog(null);notify(previous?"Оплата обновлена":"Оплата добавлена")}catch{notify("Не удалось сохранить оплату. Попробуйте ещё раз.")}};
 const remove=async(payment:Payment)=>{try{await deletePaymentTransaction(payment.id);setDialog(null);notify("Оплата удалена")}catch{notify("Не удалось удалить оплату. Попробуйте ещё раз.")}};
 const shiftMonth=(amount:number)=>{const date=new Date(year,month+amount,1);setMonth(date.getMonth());setYear(date.getFullYear())};
 const lastFor=(studentId:string)=>payments.filter(payment=>payment.studentId===studentId).sort((a,b)=>b.date.localeCompare(a.date))[0];
 return <StudentsShell active="Оплаты" toast={toast}><header className="students-header payments-header"><div><h1>Оплаты</h1><p>Платежи и остаток занятий</p></div><button className="students-add" onClick={()=>setDialog({kind:"add"})}>+ Добавить оплату</button></header>
 <div className="payment-stats"><article className="payment-stat lavender"><span>Получено за месяц</span><strong>{money(received)}</strong></article><article className="payment-stat sage"><span>Оплаченных занятий</span><strong>{paidLessons}</strong></article><article className="payment-stat peach"><span>Нужна оплата</span><strong>{needPayment}</strong></article></div>
 <section className="payer-section"><h2>Ученики</h2><div className="payer-list">{students.map((student,index)=>{const last=lastFor(student.id);return <article className="payer-card" key={student.id}><div className={`student-list-avatar avatar-${index%4}`}>{student.name.split(" ").map(part=>part[0]).join("").slice(0,2)}</div><div className="payer-name"><strong>{student.name}</strong><span>{money(currentLessonPrice(student))} / занятие</span></div><div className="payer-balance">{student.balance===0?<b>Нужна оплата</b>:<><span>Осталось</span><strong>{student.balance} занятий</strong></>}</div><div className="last-payment"><span>Последняя оплата</span><strong>{last?`${money(last.amount)} · ${last.lessonCount} занятий`:"—"}</strong></div><button onClick={()=>setDialog({kind:"add",studentId:student.id})}>Добавить оплату</button></article>})}</div></section>
 <section className="payment-history"><div className="history-heading"><h2>История оплат</h2><div><button onClick={()=>shiftMonth(-1)}>←</button><strong>{months[month]} {year}</strong><button onClick={()=>shiftMonth(1)}>→</button></div></div>{monthly.length?<div className="payment-rows">{monthly.map((payment,index)=>{const student=students.find(item=>item.id===payment.studentId);return <article className="payment-row" key={payment.id}><time>{new Date(`${payment.date}T12:00:00`).toLocaleDateString("ru-RU",{day:"numeric",month:"short"})}</time><div className={`student-list-avatar avatar-${index%4}`}>{student?.name.split(" ").map(part=>part[0]).join("").slice(0,2)}</div><strong>{student?.name??"Ученик"}</strong><span>{payment.lessonCount} занятий × {money(payment.lessonPrice)}</span><b>{money(payment.amount)}</b><details><summary>•••</summary><div><button onClick={()=>setDialog({kind:"edit",payment})}>Редактировать</button><button onClick={()=>setDialog({kind:"delete",payment})}>Удалить оплату</button></div></details></article>})}</div>:<div className="payments-empty"><img src="/asset-books-lavender.png" alt=""/><h3>Пока нет оплат</h3><p>Добавьте первую оплату, чтобы начать вести историю.</p><button className="students-add" onClick={()=>setDialog({kind:"add"})}>+ Добавить оплату</button></div>}</section>
 {(dialog?.kind==="add"||dialog?.kind==="edit")&&<PaymentForm students={students} initialStudentId={dialog.kind==="add"?dialog.studentId:undefined} initial={dialog.kind==="edit"?dialog.payment:undefined} onCancel={()=>setDialog(null)} onSave={payment=>save(payment,dialog.kind==="edit"?dialog.payment:undefined)}/>} {dialog?.kind==="delete"&&<DeletePayment payment={dialog.payment} student={students.find(item=>item.id===dialog.payment.studentId)} onCancel={()=>setDialog(null)} onDelete={()=>remove(dialog.payment)}/>}</StudentsShell>
}

function PaymentForm({students,initialStudentId,initial,onSave,onCancel}:{students:Student[];initialStudentId?:string;initial?:Payment;onSave:(payment:Payment)=>void;onCancel:()=>void}){const initialId=initial?.studentId??initialStudentId??students[0]?.id??"",initialStudent=students.find(item=>item.id===initialId)??students[0],[studentId,setStudentId]=useState(initialId),[count,setCount]=useState(initial?.lessonCount??8),[unitPrice,setUnitPrice]=useState(initial?.lessonPrice??(initialStudent?currentLessonPrice(initialStudent):0)),[amount,setAmount]=useState(initial?.amount??(initialStudent?currentLessonPrice(initialStudent):0)*8),[date,setDate]=useState(initial?.date??isoToday());const student=students.find(item=>item.id===studentId)??students[0],recommended=unitPrice*count;const chooseStudent=(id:string)=>{setStudentId(id);const next=students.find(item=>item.id===id),price=next?currentLessonPrice(next):0;setUnitPrice(price);setAmount(price*count)};const chooseCount=(value:number)=>{setCount(value);setAmount(unitPrice*value)};const submit=(event:FormEvent)=>{event.preventDefault();onSave({id:initial?.id??`payment-${Date.now()}`,studentId,date,lessonPrice:unitPrice,lessonCount:count,amount})};return <div className="student-modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onCancel()}><section className="payment-modal"><header><h2>{initial?"Редактировать оплату":"Добавить оплату"}</h2><button onClick={onCancel}>×</button></header><form onSubmit={submit}><label>Ученик<select value={studentId} onChange={event=>chooseStudent(event.target.value)}>{students.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="price-readonly"><span>Стоимость занятия</span><strong>{money(unitPrice)}</strong></div><label>Количество оплаченных занятий<input required min="1" type="number" value={count} onChange={event=>chooseCount(Math.max(1,Number(event.target.value)))}/></label><label>Сумма оплаты<input required min="0" type="number" value={amount} onChange={event=>setAmount(Number(event.target.value))}/></label><label>Дата оплаты<input required type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><div className="payment-total"><strong>{student?.name}</strong><span>{count} занятий × {money(unitPrice)}</span><b>{amount===recommended?`К оплате: ${money(amount)}`:`Фактически оплачено: ${money(amount)}`}</b></div><div className="modal-actions"><button type="button" onClick={onCancel}>Отмена</button><button className="form-save">Сохранить оплату</button></div></form></section></div>}
function DeletePayment({payment,student,onDelete,onCancel}:{payment:Payment;student?:Student;onDelete:()=>void;onCancel:()=>void}){return <div className="student-modal-backdrop"><section className="payment-modal delete-payment"><header><h2>Удалить оплату?</h2><button onClick={onCancel}>×</button></header><p>Удалить оплату <b>{student?.name}</b> на сумму <b>{money(payment.amount)}</b>? Остаток будет уменьшен на {payment.lessonCount} занятий.</p><div className="modal-actions"><button onClick={onCancel}>Отмена</button><button className="danger-button" onClick={onDelete}>Удалить оплату</button></div></section></div>}
